## Estructura Vector (arreglos)

Un vector es una secuancia de objetos de la misma clase. la primera forma de crear un vector es a partir de elementos individuales del mismo tipo.

In [ ]:
import numpy as np

In [ ]:
v=np.array([3,4,3,5,6,7,8])
v

array([3, 4, 3, 5, 6, 7, 8])

In [ ]:
v1=np.array([4,5,6,2,1,7])
print(v1)

[4 5 6 2 1 7]


### Características importantes de los vectores

a) Crear vectores especificando el tipo

In [ ]:
# Crear un vector de tipo entero
v=np.array([3,4,5,6],dtype=int)
v

array([3, 4, 5, 6])

In [ ]:
# Crear un vector de tipo float
v=np.array([3,4,5,6],dtype=float)
v

array([3., 4., 5., 6.])

In [ ]:
# Crear un vector de tipo complejo
v=np.array([3,4,5,6],dtype=complex)
v

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [ ]:
# Crear un vector de tipo boleano
v=np.array([3,4,0,6],dtype=bool)
v

array([ True,  True, False,  True])

b) Gestión de elementos de un vector mediante indices

In [ ]:
# Crear un vector de tipo entero
v=np.array([3,4,5,6,5,6,7,3,8,9],dtype=int)
v

array([3, 4, 5, 6, 5, 6, 7, 3, 8, 9])

In [ ]:
v[0]

3

In [ ]:
v[-1]

9

In [ ]:
v[:4]

array([3, 4, 5, 6])

In [ ]:
v[3:]

array([6, 5, 6, 7, 3, 8, 9])

In [ ]:
v[2:6]

array([5, 6, 5, 6])

In [ ]:
v[::2]

array([3, 5, 5, 7, 8])

c) Funciones para insertar datos en un arreglo

In [ ]:
# Crear un vector de tipo entero
v=np.array([3,4,5,6,5,6,7,3,8,9],dtype=int)
v

array([3, 4, 5, 6, 5, 6, 7, 3, 8, 9])

* Remplaza cada elemento del arreglo con 10

In [ ]:
v.fill(10)

In [ ]:
v

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [ ]:
# otra forma

In [ ]:
v[:]=20
v

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [ ]:
v[3:]=100
v

array([ 20,  20,  20, 100, 100, 100, 100, 100, 100, 100])

d) Funciones matemáticas para arreglos

In [ ]:
# creamos un arreglo

In [ ]:
v=np.array([2,3,4,5,6,4,7,9,8,6,9])
v

array([2, 3, 4, 5, 6, 4, 7, 9, 8, 6, 9])

In [ ]:
# Calcula el producto de los elementos de un vector
np.prod(v)

78382080

In [ ]:
# Calcula el indice de mayor valor
np.argmax(v)

7

In [ ]:
# Calcula el indice del menor valor
np.argmin(v)

0

In [ ]:
# Calcula la media aritmetica
np.mean(v)

5.7272727272727275

In [ ]:
# Calcula la desviación estandar
np.std(v)

2.259964162664737

In [ ]:
# calcula la mediana
np.median(v)

6.0

In [ ]:
# Calcula la suma de los elementos
np.sum(v)

63

In [ ]:
# Calcula la suma acumulada
np.cumsum(v)

array([ 2,  5,  9, 14, 20, 24, 31, 40, 48, 54, 63])

In [ ]:
# realiza restas sucesivas entre sus elementos
np.diff(v)

array([ 1,  1,  1,  1, -2,  3,  2, -1, -2,  3])

## Matrices

Una matriz es una estructura de datos, que tiene m filas y n columnas, es decir dado un conjunto de datos puede ser organizado en una estructura bidimensional

In [ ]:
import numpy as np
M=np.array([[2,3,4],[4,5,6],[1,5,3],[2,5,6]])
M

array([[2, 3, 4],
       [4, 5, 6],
       [1, 5, 3],
       [2, 5, 6]])

 a) Realizar las consultas de elementos de una Matriz

In [ ]:
# Despliega el elemento de la tercera fila y la tercera columna de la matriz M
M[2,2]

3

In [ ]:
M[1,2]

6

In [ ]:
M[0,2]

4

In [ ]:
M[1,0]

4

In [ ]:
M

array([[2, 3, 4],
       [4, 5, 6],
       [1, 5, 3],
       [2, 5, 6]])

In [ ]:
M[2:,:2]

array([[1, 5],
       [2, 5]])

In [ ]:
M

array([[2, 3, 4],
       [4, 5, 6],
       [1, 5, 3],
       [2, 5, 6]])

In [ ]:
M[0,2]

4

In [ ]:
M[2:,1]

array([5, 5])

In [ ]:
M[2:,:2]

array([[1, 5],
       [2, 5]])

Despliega la tercera columna, es decir todas las filas en la columna 2

In [ ]:
M[:,-1]

array([4, 6, 3, 6])

In [ ]:
M

array([[2, 3, 4],
       [4, 5, 6],
       [1, 5, 3],
       [2, 5, 6]])

In [ ]:
M[1:3,0:2]

array([[4, 5],
       [1, 5]])

In [ ]:
M[1:,1:]

array([[5, 6],
       [5, 3],
       [5, 6]])

In [ ]:
M

array([[2, 3, 4],
       [4, 5, 6],
       [1, 5, 3],
       [2, 5, 6]])

In [ ]:
M[1:3,1:3]

array([[5, 6],
       [5, 3]])

In [ ]:
M[2:4,0:2]

array([[1, 5],
       [2, 5]])

In [ ]:
M[1:3,[0,2]]

array([[4, 6],
       [1, 3]])

Asignación de elementos en una matriz

In [ ]:
M[-1,:]=10
M

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 1,  5,  3],
       [10, 10, 10]])

In [ ]:


M[2:,1:]=100
M

array([[  2,   3,   4],
       [  4,   5,   6],
       [  1, 100, 100],
       [ 10, 100, 100]])

In [ ]:
import numpy as np
M=np.array([[2,3,4],[4,5,6],[1,5,3],[2,5,6]])
M

array([[2, 3, 4],
       [4, 5, 6],
       [1, 5, 3],
       [2, 5, 6]])

In [ ]:
M[1:3,:]=100
M

array([[  2,   3,   4],
       [100, 100, 100],
       [100, 100, 100],
       [  2,   5,   6]])

In [ ]:
M[2:,1:]=0
M

array([[  2,   3,   4],
       [100, 100, 100],
       [100,   0,   0],
       [  2,   0,   0]])

In [ ]:
M[:2,:2]=800
M

array([[800, 800,   4],
       [800, 800, 100],
       [100,   0,   0],
       [  2,   0,   0]])

Funciones especiales de matrices

In [ ]:
import numpy as np
M=np.array([[2,3,4],[4,5,6],[1,5,3],[2,5,6]])
M


array([[2, 3, 4],
       [4, 5, 6],
       [1, 5, 3],
       [2, 5, 6]])

In [ ]:
# calcula la dimensión de la matriz
np.ndim(M)

2

In [ ]:
# calcula la cantidad de elementos de una matriz
np.size(M)

12

In [ ]:
# Calcula la cantidad de filas y columnas de la matriz
[m,n]=np.shape(M)
[m,n]

[4, 3]

Convertir un arreglo unidimensional a un arreglo bidimensional

In [ ]:
import numpy as np
A=np.arange(9)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
B=A.reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Convertir una matriz en una columna

In [ ]:
C=B.reshape(9,1)
C

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
D=B.reshape(1,9)
D

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

Operaciones con Matrices

In [ ]:
A=np.array([[3,4],[3,5]])
B=np.array([[4,5],[6,7]])
A

array([[3, 4],
       [3, 5]])

In [ ]:
B

array([[4, 5],
       [6, 7]])

In [ ]:
# sumar A y B
A+B

array([[ 7,  9],
       [ 9, 12]])

In [ ]:
# producto de A y B
A*B

array([[12, 20],
       [18, 35]])

In [ ]:
# Diferencia
A-B

array([[-1, -1],
       [-3, -2]])

In [ ]:
# división
A/B

array([[0.75      , 0.8       ],
       [0.5       , 0.71428571]])

In [ ]:
A**2

array([[ 9, 16],
       [ 9, 25]])

In [ ]:
# multiplicar dos matrices

In [ ]:
np.dot(A,B)

array([[36, 43],
       [42, 50]])

In [ ]:
A@B

array([[36, 43],
       [42, 50]])

In [ ]:
A


array([[3, 4],
       [3, 5]])

In [ ]:
B

array([[4, 5],
       [6, 7]])

In [ ]:
#suma de los elementos de una matriz
np.sum(A)

15

In [ ]:
#producto de los elementos de A
np.prod(A)

180

In [ ]:
# calcula la media de A
np.mean(A)

3.75

In [ ]:
# Calcula el maximo de A
np.max(A)

5

In [ ]:
# Calcula el minimo de A
np.min(A)

3

In [ ]:
# Calcula la desviación estandar
np.std(A)

0.82915619758885

In [ ]:
# Calcula la mediana
np.median(A)

3.5

In [ ]:
#ordena los elementos de B
np.sort(B)

array([[4, 5],
       [6, 7]])

In [ ]:
# Calcula la suma acumulada de A

In [ ]:
np.cumsum(A)

array([ 3,  7, 10, 15])

In [ ]:
import statistics as stat

edades = [21, 17, 89, 76, 32, 21, 45, 21, 89, 21, 15, 89, 21]

moda=stat.mode(edades)
moda

21

In [ ]:
# Calcular la traza de una matriz: suma diagonal
A=np.array([[2,3,4],[4,5,6],[6,7,8]])
A

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.trace(A)

15

In [ ]:
# calcula la traspuesta de la matriz A
np.transpose(A)

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [ ]:
# otro metodo para calcular la transpuesta
A.T

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [ ]:
# matriz triangular inferior
np.tril(A)

array([[2, 0, 0],
       [4, 5, 0],
       [6, 7, 8]])

In [ ]:
# matriz triangular superior
np.triu(A)

array([[2, 3, 4],
       [0, 5, 6],
       [0, 0, 8]])

In [ ]:
# La inversa de la matriz
np.linalg.inv(A)

array([[ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14],
       [-1.12589991e+15,  2.25179981e+15, -1.12589991e+15],
       [ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14]])

In [ ]:
# Calcula el determinante
np.linalg.det(A)

-3.552713678800511e-15

## Estructura Tupla

Una tupla es una colección de datos que puede tener diferente tipo, los datosn se escriben entre paréntesis separados por comas.

In [ ]:
T=(12,13,15,35,26)

In [ ]:
T

(12, 13, 15, 35, 26)

In [ ]:
T[0]

12

In [ ]:
T[4]

26

In [ ]:
T[-1]

26

In [ ]:
T[:2]

(12, 13)

In [ ]:
T[3:]

(35, 26)

In [ ]:
T[2:4]

(15, 35)

Concatenar tuplas

In [ ]:
T1=(2,3,4,5)
T2=(4,5,6,7)
T3=T1+T2
T3

(2, 3, 4, 5, 4, 5, 6, 7)

Funciones aplicables a tuplas

In [ ]:
T=(6,3,6,5,6,7,8)
T

(6, 3, 6, 5, 6, 7, 8)

In [ ]:
# Cantidad de elementos de una tupla
len(T)

7

In [ ]:
# Camcula el maximo en la tupla
max(T)

8

In [ ]:
min(T)

3

In [ ]:
# cuenta la coincidencia
T.count(6)

3

In [ ]:
T=(6,3,6,5,6,7,8,7,7,7,7)
T

(6, 3, 6, 5, 6, 7, 8, 7, 7, 7, 7)

In [ ]:
# Calcual la moda de una lista
maxi=0
for ele in T:
  s=T.count(ele)
  if maxi<s:
    maxi=s
    dat=ele
print(f"La moda es:{dat} se repite {maxi} veces")


La moda es:7 se repite 5 veces


 ## Estructura Conjunto

In [ ]:
# definamos un conjunto

In [ ]:
A={3,4,5,6,5,5}
A

{3, 4, 5, 6}

In [ ]:
B=set([3,4,5,6,7])
B

{3, 4, 5, 6, 7}

Operaciones basicas de conjuntos


In [ ]:
A={2,3,4,5,6,7}
B={3,8,9,4,5}
A

{2, 3, 4, 5, 6, 7}

In [ ]:
# Union de conjuntos
A|B

{2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
# Calcula la intersección de conjuntos
A&B

{3, 4, 5}

In [ ]:
# Calcula la diferencia
A-B

{2, 6, 7}

In [ ]:
# pertenencia de un elemento
3 in A

True

In [ ]:
100 in A

False

In [ ]:
# Convertir un conjunto a lista
L=list(A)
L

[2, 3, 4, 5, 6, 7]

In [ ]:
# Cadena de caracteres convertido a conjuntos
C= "programando"
A=set(C)
A

{'a', 'd', 'g', 'm', 'n', 'o', 'p', 'r'}

In [ ]:
L=list(C)
L

['p', 'r', 'o', 'g', 'r', 'a', 'm', 'a', 'n', 'd', 'o']

Funciones aplicables a conjuntos

In [ ]:
len(A)

8

In [ ]:
A={2,3,4,5}

In [ ]:
# suma
sum(A)

14

In [ ]:
Z={3,4,5,6}
Z

{3, 4, 5, 6}

In [ ]:
sum(Z)

18

In [ ]:
min(Z)

3

In [ ]:
max(Z)

6

In [ ]:
Z.add(20)

In [ ]:
Z

{3, 4, 5, 6, 20}

In [ ]:
Z.remove(5)
Z

{3, 4, 6, 20}

In [ ]:
Z.pop()
Z

{4, 6, 20}